- hosts: control 
  become: yes
  tasks:
    - name: "TASK 1: Initialize the kubernetes cluster using kubeadm"
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: "TASK 2: Creates .kube directory for kubeconfig setup"
      become: yes
      become_user: vagrant
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: "TASK 3: Copies k8s admin.conf to .kube/config for vagrant user"
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: vagrant

    - name: "TASK 4: Install calico Pod network"
      become: yes
      become_user: vagrant
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
      args:
        chdir: $HOME
        
    - name: "TASK 5: Generate Join command for workers to join the cluster"
      become: yes
      become_user: vagrant
      command: kubeadm token create  --print-join-command
      register: kubeadm_join_command

    - name: "TASK 6: Print the output of variable kubeadm_join_command for debug reasons"
      debug:
        msg: "{{ kubeadm_join_command.stdout }}"

    - name: "TASK 7: Copy join command to a local file."
      become: yes
      local_action: copy content="{{ kubeadm_join_command.stdout_lines[0] }}" dest="/tmp/kubeadm_join_command" mode=0777

  handlers:   
    - name: docker started
      service: name=docker state=started 

