---
- name: "PLAY 1 : Install kubernentes"
  hosts: "control, nodes"
  remote_user: vagrant
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes 
  connection: ssh 

  # pre_tasks: 
  #  - name: Update yum cache if needed. 
  #    dnf: update_cache=yes  
  #    # in case of Debian based os the cache valid time can added to this pre_task cache_valid_time=3600 

  tasks:
     - name: "TASK: disable firewall service for labs" 
       service:
         name: firewalld
         state: stopped
         enabled: false

     - name: "TASK: Disable SWAP"
       shell: swapoff -a

     - name: "TASK: Disable SWAP in fstab"
       lineinfile:
         path: /etc/fstab
         regexp: 'swap'
         state: absent

     - name: "TASK: disable SELinux"
       command: setenforce 0
       ignore_errors: yes

     - name: "TASK: disable SELinux on reboot" 
       selinux:
         state: disabled  
     - name: "TASK: Enable kernel module bridge" 
       modprobe:  
         name: br_netfilter   
         state: present     

     - name: "TASK: ensure net.bridge.bridge-nf-call-ip6tables is set to 1" 
       sysctl:
         name: net.bridge.bridge-nf-call-ip6tables 
         value: 1
         state: present

     - name: "TASK: ensure net.bridge.bridge-nf-call-iptables is set to 1" 
       sysctl:
         name: net.bridge.bridge-nf-call-iptables
         value: 1
         state: present

     - name: "TASK 5: Enable ip forwarding"
       sysctl:      
         name: net.ipv4.ip_forward 
         value: 1 
         state: present 

     - name: "TASK 6: Apply new sysctl settings"  
       command: sysctl --system 
   
     - name: "TASK: Add docker repo" 
       shell: |
               yum install -y yum-utils
               yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo  
               yum-config-manager --enable ol8_addons
       when: ansible_os_family == "RedHat"

     - name: "TASK: Install docker and dependencies" 
       dnf: 
         name: "{{ item }}" 
         state: present 
         allowerasing: yes 
         disablerepo: kubernetes 
       loop: 
         - docker-ce
         - docker-ce-cli 
         - containerd.io 

     - name: "TASK 11: Add k8s repository"
       yum_repository:       
         name: Kubernetes
         description: Kubernetes Repository 
         baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
         #baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
         enabled: yes 
         gpgcheck: yes 
         gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
           - https://packages.cloud.google.com/yum/doc/yum-key.gpg
           - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg 
         exclude: kubelet, kubeadm, kubectl
       when: ansible_os_family == "RedHat"

     - name: "TASK 12: Install kubernetes(kubelet, kubeadm, kubectl)"  
       yum:         
         name: "{{ item }}" 
         state: present 
         disable_excludes: kubernetes
       loop: 
         - kubelet
         - kubeadm
         - kubectl 
       when: ansible_os_family == "RedHat"

     - name: "TASK 13: Start docker and kubelet" 
       service: 
         name: "{{ item }}" 
         state: started  
       loop: 
         - docker 
         - kubelet  

     - name: "TASK 14: Enable docker and kubelet" 
       service: 
         name: "{{ item }}" 
         state: enabled  
       loop: 
         - docker 
         - kubelet  
