- hosts: nodes  
  become: yes
  gather_facts: yes

  tasks:
   - name: "TASK 1: Copy the join command from Ansible deployer to the worker nodes."
     become: yes
     copy:
       src: /tmp/kubeadm_join_command
       dest: /tmp/kubeadm_join_command
       mode: 0777

   - name: "TASK 2: Join the Worker nodes to the cluster."
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: join_command_result 

   - name: "TASK 3: Print result of Join command"
     debug:  
       msg: "{{ join_command_result }}" 

