---
- name: "PLAY 1 -  Create needed users" 
  hosts: 'nodes, control'
  become: yes

  tasks:
    - name: "TASK 1:  Create the kube user account"
      user: name=kube append=yes state=present createhome=yes shell=/bin/bash

    - name: "TASK 2: Allow 'kube' to use sudo without needing a password" 
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: "TASK 3: Set up authorized keys for the kube user"
      authorized_key: user=kube key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
